// Diagnostic: test each import group from main.tsx
process.stderr.write("DIAG: starting\n")

try {
  process.stderr.write("DIAG: importing startupProfiler...\n")
  await import('./utils/startupProfiler.js')
  process.stderr.write("DIAG: importing settings mdm...\n")
  await import('./utils/settings/mdm/rawRead.js')
  process.stderr.write("DIAG: importing keychainPrefetch...\n")
  await import('./utils/secureStorage/keychainPrefetch.js')
  process.stderr.write("DIAG: importing commander...\n")
  await import('@commander-js/extra-typings')
  process.stderr.write("DIAG: importing constants/oauth...\n")
  await import('./constants/oauth.js')
  process.stderr.write("DIAG: importing constants/product...\n")
  await import('./constants/product.js')
  process.stderr.write("DIAG: importing context...\n")
  await import('./context.js')
  process.stderr.write("DIAG: importing entrypoints/init...\n")
  await import('./entrypoints/init.js')
  process.stderr.write("DIAG: importing history...\n")
  await import('./history.js')
  process.stderr.write("DIAG: importing replLauncher...\n")
  await import('./replLauncher.js')
  process.stderr.write("DIAG: importing growthbook...\n")
  await import('./services/analytics/growthbook.js')
  process.stderr.write("DIAG: importing bootstrap...\n")
  await import('./services/api/bootstrap.js')
  process.stderr.write("DIAG: importing policyLimits...\n")
  await import('./services/policyLimits/index.js')
  process.stderr.write("DIAG: importing tools...\n")
  await import('./tools.js')
  process.stderr.write("DIAG: importing utils/config...\n")
  await import('./utils/config.js')
  process.stderr.write("DIAG: importing main chunk done\n")
} catch(e) {
  process.stderr.write("DIAG ERROR: " + String(e) + "\n")
  if (e instanceof Error) process.stderr.write(e.stack + "\n")
}
