process.stderr.write("DIAG4: start\n")
try {
  process.stderr.write("DIAG4: ./hooks/useCommandQueue.js\n"); await import("./hooks/useCommandQueue.js")
  process.stderr.write("DIAG4: ./hooks/useIdeAtMentioned.js\n"); await import("./hooks/useIdeAtMentioned.js")
  process.stderr.write("DIAG4: ./state/AppState.js\n"); await import("./state/AppState.js")
  process.stderr.write("DIAG4: ./utils/cwd.js\n"); await import("./utils/cwd.js")
  process.stderr.write("DIAG4: ./utils/messageQueueManager.js\n"); await import("./utils/messageQueueManager.js")
  process.stderr.write("DIAG4: ./commands/fast/fast.js\n"); await import("./commands/fast/fast.js")
  process.stderr.write("DIAG4: ./commands/review/ultrareviewEnabled.js\n"); await import("./commands/review/ultrareviewEnabled.js")
  process.stderr.write("DIAG4: ./commands/terminalSetup/terminalSetup.js\n"); await import("./commands/terminalSetup/terminalSetup.js")
  process.stderr.write("DIAG4: ./context/overlayContext.js\n"); await import("./context/overlayContext.js")
  process.stderr.write("DIAG4: ./utils/thinking.js\n"); await import("./utils/thinking.js")
  process.stderr.write("DIAG4: ./utils/ultraplan/keyword.js\n"); await import("./utils/ultraplan/keyword.js")
  process.stderr.write("DIAG4: ./components/AutoModeOptInDialog.js\n"); await import("./components/AutoModeOptInDialog.js")
  process.stderr.write("DIAG4: ./components/BridgeDialog.js\n"); await import("./components/BridgeDialog.js")
  process.stderr.write("DIAG4: ./components/ModelPicker.js\n"); await import("./components/ModelPicker.js")
  process.stderr.write("DIAG4: ./components/TextInput.js\n"); await import("./components/TextInput.js")
  process.stderr.write("DIAG4: ./components/ThinkingToggle.js\n"); await import("./components/ThinkingToggle.js")
  process.stderr.write("DIAG4: ./components/tasks/BackgroundTasksDialog.js\n"); await import("./components/tasks/BackgroundTasksDialog.js")
  process.stderr.write("DIAG4: ./components/teams/TeamsDialog.js\n"); await import("./components/teams/TeamsDialog.js")
  process.stderr.write("DIAG4: ./components/VimTextInput.js\n"); await import("./components/VimTextInput.js")
  process.stderr.write("DIAG4: done\n")
} catch(e) { process.stderr.write("ERR: "+String(e)+"\n") }
